<section id="widget-grid" class="">
	<article class="">
		<div id="wid-id-18" class="jarviswidget jarviswidget-color-red jarviswidget-sortable" style="" role="widget">
			<header role="heading">
				<div class="jarviswidget-ctrls" role="menu">
					<a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-toggle-btn" href="javascript:void(0);" data-original-title="Collapse">
						<i class="fa fa-minus "></i>
					</a>
					<a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-fullscreen-btn" href="javascript:void(0);" data-original-title="Fullscreen">
						<i class="fa fa-expand "></i>
					</a>
					<a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-delete-btn" href="javascript:void(0);" data-original-title="Delete">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<h2>
					<strong>Fixed</strong>
					<i>Height</i>
				</h2>
				<span class="jarviswidget-loader">
					<i class="fa fa-refresh fa-spin"></i>
				</span>
			</header>
			<!-- widget div-->
			<div role="content">
				<!-- widget edit box -->
				<div class="jarviswidget-editbox">
					<!-- This area used as dropdown edit box -->
					<input type="text" class="form-control">
						<span class="note">
							<i class="fa fa-check text-success"></i>
							Change title to update and save instantly!
						</span>
				</div>
				<!-- end widget edit box -->
				<!-- widget content -->
				<div class="widget-body no-padding">
					<div style="height:740px; overflow-y: scroll;" class="custom-scroll table-responsive">
						<blockquote class="instagram-media" data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
							<div style="padding:8px;">
								<div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;">
									<div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;">
									</div>
								</div>
								<p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">
									<a href="https://instagram.com/p/5CtI6dE6Xa/" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_top">
										Фото опубликовано Podlesnaya_A (@aaaaaaaaaaaaaaaaaaaaaaa_aaaa)
									</a>
									<time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-07-12T16:09:24+00:00">
										Июл 12 2015 в 9:09 PDT
									</time>
								</p>
							</div>
						</blockquote>
						<script async defer src="//platform.instagram.com/en_US/embeds.js">
						</script>
					</div>
				</div>
				<!-- end widget content -->
			</div>
			<!-- end widget div -->

		</div>
	</article>
</section>