<?php $this->partial('partials/head') ?>
<!--================================================== -->
<?php $this->partial('partials/header', $this); ?>
<!--================================================== -->
<?php $this->partial('partials/nav-menu'); ?>
<!--================================================== -->
		<?php /* MAIN PANEL */ ?>
		<div id="main" role="main">
			<!--================================================== -->
			<?php $this->partial('partials/ribbon'); ?>
			<!--================================================== -->
			<?php /* MAIN CONTENT */ ?>
			<div id="content">
				<!--================================================== -->
				<?php /* ?>
				<!--
				The ID "widget-grid" will start to initialize all widgets below
				You do not need to use widgets if you dont want to. Simply remove
				the <section></section> and you can use wells or panels instead
				-->
				<?php /**/ ?>
				<!--================================================== -->
				<?php echo $this->getContent() ?>
				<!--================================================== -->
			</div>
			<?php /* END MAIN CONTENT */ ?>
			<!--================================================== -->
		</div>
		<?php /* END MAIN PANEL */ ?>
		<!--================================================== -->
		<?php $this->partial('partials/footer'); ?>
		<!--================================================== -->
		<!--================================================== -->
		<?php $this->partial('partials/shortcut-area'); ?>
		<!--================================================== -->
		<?php $this->partial('partials/common_js'); ?>
	</body>
</html>