			<?php /* advanced dropdown */ ?>
			<div class="project-context hidden-xs">

				<span class="label">Quick access:</span>
				<span class="project-selector dropdown-toggle" data-toggle="dropdown">Recent <i class="fa fa-angle-down"></i></span>

				<?php /* Suggestion: populate this list with fetch and push technique */ ?>
				<ul class="dropdown-menu">
					<li>
						<a href="javascript:void(0);">First item</a>
					</li>
					<li>
						<a href="javascript:void(0);">Second item</a>
					</li>
					<li>
						<a href="javascript:void(0);">Third item</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
					</li>
				</ul>
				<?php /* end dropdown-menu */ ?>
			</div>
			<?php /* end advanced dropdown */ ?>