<aside id="left-panel">
	<nav>
		<ul>
		<?php //---------------------------------------?>
			<li>
				<a>
					<i class="fa fa-lg fa-fw fa-home"></i>
					<span class="menu-item-parent">Main</span>
				</a>
				<ul>
					<li id="sidebarLink-index-index">
						<a href="/">Главная</a>
					</li>
					<li>
						<a href="">Статистика</a>
					</li>
					<li>
						<a href="">Квартиры</a>
					</li>
					<li id="sidebarLink-stock-manage">
						<a href="/stock/manage">Рынок</a>
					</li>
					<li>
						<a href="">Падающие в цене</a>
					</li>
				</ul>
			</li>
		</ul>
	</nav>
	<span class="minifyme" data-action="minifyMenu">
		<i class="fa fa-arrow-circle-left hit"></i>
	</span>

</aside>