<?php /* RIBBON */ ?>
<div id="ribbon">

	<span class="ribbon-button-alignment">
		<span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
			<i class="fa fa-refresh"></i>
		</span>
	</span>

	<?php /* BREADCRUMB */ ?>
	<ol class="breadcrumb" id="breadcrumb">
	</ol>
	<?php /* END BREADCRUMB */ ?>

	<?php /* ?>
	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->
	<?php /**/ ?>
</div>
<?php /* END RIBBON */ ?>
<script>
var breadcrumb = $('#breadcrumb');
var activeLi = $('#sidebarLink-<?php echo $this->dispatcher->getControllerName()?>-<?php echo $this->dispatcher->getActionName()?>');
$(document).ready(function(){
	addActive();
	addBreadcrumbs();
})

function addActive()
{
	activeLi.addClass('active');
	activeLi.parent().attr('style', 'display:block;');
	activeLi.parent().parent().addClass('open');
}

function addBreadcrumbs()
{
	breadcrumb.prepend('<li>' + activeLi.children('a').text() + '</li>');
	breadcrumb.prepend('<li>' + activeLi.parent().parent().children('a').children('span').text() + '</li>');
}
</script>
