<!DOCTYPE html>
<html lang="en-us" id="lock-page">
	<head>
		<meta charset="utf-8">
		<title>Авторизация</title>
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!-- #CSS Links -->
		<!-- Basic Styles -->
		<?php echo Phalcon\Tag::stylesheetLink('css/bootstrap.min.css'); ?>
		<?php echo Phalcon\Tag::stylesheetLink('css/font-awesome.min.css'); ?>

		<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
		<?php echo Phalcon\Tag::stylesheetLink('css/smartadmin-production-plugins.min.css'); ?>
		<?php echo Phalcon\Tag::stylesheetLink('css/smartadmin-production.min.css'); ?>
		<?php echo Phalcon\Tag::stylesheetLink('css/smartadmin-skins.min.css'); ?>

		<!-- SmartAdmin RTL Support -->
		<?php echo Phalcon\Tag::stylesheetLink('css/smartadmin-rtl.min.css'); ?>

		<!-- Demo purpose only: goes with demo.js, you can delete this css when designing your own WebApp -->
		<?php echo Phalcon\Tag::stylesheetLink('css/demo.min.css'); ?>

		<!-- page related CSS -->
		<?php echo Phalcon\Tag::stylesheetLink('css/lockscreen.min.css'); ?>

		<!-- #FAVICONS -->
		<link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
		<link rel="icon" href="/img/favicon.ico" type="image/x-icon">

		<!-- #GOOGLE FONT -->
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">
	</head>

	<body>
		<div id="main" role="main">
			<?php echo $this->getContent() ?>
		</div>

		<!--================================================== -->

		<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
		<?php echo Phalcon\Tag::javascriptInclude("js/plugin/pace/pace.min.js"); ?>

	    <!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
	    <?php echo Phalcon\Tag::javascriptInclude("js/jQuery/jquery-2.1.1.min.js"); ?>
        <?php echo Phalcon\Tag::javascriptInclude("js/jQuery/jquery-ui-1.10.3.min.js"); ?>

		<!-- IMPORTANT: APP CONFIG -->
        <?php echo Phalcon\Tag::javascriptInclude("js/app.config.js"); ?>

		<!-- JS TOUCH : include this plugin for mobile drag / drop touch events
		<script src="js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script> -->

		<!-- BOOTSTRAP JS -->
        <?php echo Phalcon\Tag::javascriptInclude("js/bootstrap/bootstrap.min.js"); ?>

		<!-- JQUERY VALIDATE -->
        <?php echo Phalcon\Tag::javascriptInclude("js/plugin/jquery-validate/jquery.validate.min.js"); ?>

		<!-- JQUERY MASKED INPUT -->
        <?php echo Phalcon\Tag::javascriptInclude("js/plugin/masked-input/jquery.maskedinput.min.js"); ?>

		<!-- MAIN APP JS FILE -->
        <?php echo Phalcon\Tag::javascriptInclude("js/app.min.js"); ?>

	</body>
</html>