<form action="" class="lockscreen animated flipInY" method="post">
	<div class="logo">
		<h1 class="semi-bold"><img alt="Convextra" src="img/logo200.png"> Convextra</h1>
	</div>
	<div>
		<img alt="" src="img/fox.png">
		<div>
			<h1>
				<i class="fa fa-user fa-2x text-muted air air-top-right hidden-mobile"></i>
				JonKofee
				<small>
					<i class="fa fa-lock text-muted"></i>
					&nbsp;Locked
				</small>
			</h1>
			<div class="input-group hide">
				<input type="text" placeholder="Login" required="required" value="admin" id="login" name="login">
			</div>
			<div class="input-group">
				<input class="form-control" type="password" placeholder="Password" required="required" value="" id="password" name="password">
				<div class="input-group-btn">
					<button class="btn btn-primary" type="submit">
						<i class="fa fa-key"></i>
						Sign in
					</button>
				</div>
			</div>
		</div>
	</div>
	<p class="font-xs margin-top-5">
		Copyright Convextra 2015-2020.

	</p>
</form>